# Generated by Django 5.0.2 on 2026-01-20 11:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('nif', models.CharField(max_length=50, unique=True, verbose_name='NIF')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='NoteDeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=15, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tva', models.BooleanField(default=False, verbose_name='TVA')),
                ('devise', models.CharField(choices=[('EUR', 'Euro'), ('DOLLAR', 'Dollar'), ('MRU', 'Ouguiya'), ('XOF', 'Franc CFA')], default='MRU', max_length=10)),
            ],
            options={
                'verbose_name': 'Note de frais',
                'verbose_name_plural': 'Notes de frais',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('camion', models.CharField(max_length=100)),
                ('date_arrivee', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('arrive', 'Arrivé'), ('sortie', 'Sorti')], default='arrive', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('assistant', 'Assistant'), ('agent_port', 'Agent Port'), ('comptable', 'Comptable'), ('directeur_operations', 'Directeur des Opérations'), ('directeur_general', 'Directeur Général')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=15, unique=True)),
                ('port_arrive', models.CharField(max_length=255, verbose_name="Port d'arrivée")),
                ('vessel', models.CharField(max_length=255)),
                ('voyage', models.CharField(max_length=100)),
                ('eta', models.DateTimeField(verbose_name='ETA (Estimated Time of Arrival)')),
                ('etd', models.DateTimeField(verbose_name='ETD (Estimated Time of Departure)')),
                ('bl', models.CharField(max_length=100, verbose_name='Bill of Lading')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tva', models.BooleanField(default=False, verbose_name='TVA')),
                ('devise', models.CharField(choices=[('EUR', 'Euro'), ('DOLLAR', 'Dollar'), ('MRU', 'Ouguiya'), ('XOF', 'Franc CFA')], default='MRU', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='api.client')),
            ],
            options={
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=15, unique=True)),
                ('port_arrive', models.CharField(max_length=255, verbose_name="Port d'arrivée")),
                ('vessel', models.CharField(max_length=255)),
                ('voyage', models.CharField(max_length=100)),
                ('eta', models.DateTimeField(verbose_name='ETA (Estimated Time of Arrival)')),
                ('etd', models.DateTimeField(verbose_name='ETD (Estimated Time of Departure)')),
                ('bl', models.CharField(max_length=100, verbose_name='Bill of Lading')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tva', models.BooleanField(default=False, verbose_name='TVA')),
                ('devise', models.CharField(choices=[('EUR', 'Euro'), ('DOLLAR', 'Dollar'), ('MRU', 'Ouguiya'), ('XOF', 'Franc CFA')], default='MRU', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='api.client')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.IntegerField()),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.devis')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.IntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.facture')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNoteDeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nourriture', 'Nourriture'), ('hebergement', 'Hébergement'), ('medicament', 'Médicament'), ('carburant', 'Carburant'), ('entretien', 'Entretien'), ('telecom', 'Télécom'), ('avance', 'Avance'), ('divers', 'Divers')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note_de_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.notedefrais')),
            ],
        ),
    ]
