# Generated by Django 5.0.2 on 2026-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotedefrais',
            name='libelle',
            field=models.CharField(default='Essence', max_length=255),
        ),
        migrations.AddField(
            model_name='itemnotedefrais',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='attente', max_length=20),
        ),
    ]
