# Generated by Django 5.0.2 on 2026-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_piecejointe_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='type',
            field=models.CharField(blank=True, default='Annotation', max_length=100, null=True),
        ),
    ]
