# Generated by Django 5.0.2 on 2026-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemnotedefrais_libelle_itemnotedefrais_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnotedefrais',
            name='status',
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='attente', max_length=20),
        ),
    ]
