# Generated by Django 5.0.2 on 2026-02-04 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_itemnotedefrais_status_notedefrais_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('objet_commande', models.TextField(verbose_name='Objet de la commande')),
                ('date', models.DateField()),
                ('tva', models.BooleanField(default=False, verbose_name='TVA incluse')),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande_crees', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ExpressionBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=15, unique=True)),
                ('bl_awb', models.CharField(max_length=100, verbose_name='BL / AWB')),
                ('navire', models.CharField(max_length=255)),
                ('eta', models.DateTimeField(verbose_name='ETA (Estimated Time of Arrival)')),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('valide', 'Validée'), ('rejete', 'Rejetée')], default='attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tva', models.BooleanField(default=False, verbose_name='TVA')),
                ('devise', models.CharField(choices=[('EUR', 'Euro'), ('DOLLAR', 'Dollar'), ('MRU', 'Ouguiya'), ('XOF', 'Franc CFA')], default='MRU', max_length=10)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('client_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expressions_besoin', to='api.client', verbose_name='Client / Bénéficiaire')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expressions_besoin_creees', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressions_besoin_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expression de besoin',
                'verbose_name_plural': 'Expressions de besoin',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ItemBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Article')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemExpressionBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Essence', max_length=255)),
                ('type', models.CharField(choices=[('nourriture', 'Nourriture'), ('hebergement', 'Hébergement'), ('medicament', 'Médicament'), ('carburant', 'Carburant'), ('entretien', 'Entretien'), ('telecom', 'Télécom'), ('avance', 'Avance'), ('divers', 'Divers')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expression_besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.expressionbesoin')),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=20)),
                ('numero_bordereau', models.CharField(max_length=100)),
                ('observation', models.TextField(blank=True, null=True)),
                ('quantite', models.IntegerField()),
                ('camion', models.CharField(max_length=100)),
                ('date_rotation', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rotations',
                'ordering': ['-date_rotation'],
            },
        ),
        migrations.CreateModel(
            name='RotationEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bordereau', models.CharField(max_length=100)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField()),
                ('camion', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations_entrantes', to='api.client')),
            ],
            options={
                'verbose_name': 'Rotation entrante',
                'verbose_name_plural': 'Rotations entrantes',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='RotationSortante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bordereau', models.CharField(max_length=100)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField()),
                ('camion', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations_sortantes', to='api.client')),
            ],
            options={
                'verbose_name': 'Rotation sortante',
                'verbose_name_plural': 'Rotations sortantes',
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de matériel',
                'verbose_name_plural': 'Types de matériel',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AddField(
            model_name='devis',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devis_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='attente', max_length=20),
        ),
        migrations.AddField(
            model_name='devis',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_privee',
            field=models.BooleanField(default=False, verbose_name='Facture privée'),
        ),
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='attente', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='bl_awb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BL / AWB'),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='client_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_frais', to='api.client', verbose_name='Client / Bénéficiaire'),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_frais_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA (Estimated Time of Arrival)'),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='navire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_frais_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='expression_besoin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_frais', to='api.expressionbesoin'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='api.fournisseur'),
        ),
        migrations.AddField(
            model_name='itemboncommande',
            name='bon_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.boncommande'),
        ),
        migrations.AddField(
            model_name='rotationsortante',
            name='type_materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations_sortantes', to='api.typemateriel'),
        ),
        migrations.AddField(
            model_name='rotationentrante',
            name='type_materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations_entrantes', to='api.typemateriel'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations', to='api.typemateriel', verbose_name='Type de produit'),
        ),
    ]
