# Generated by Django 5.0.2 on 2026-01-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dossier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoiteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(editable=False, unique=True)),
                ('taille', models.IntegerField(default=50, help_text='Taille en nombre de dossiers')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='boite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='api.boitearchive'),
        ),
    ]
