# Generated by Django 5.0.2 on 2026-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boncommande_expressionbesoin_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
