# Generated by Django 5.0.2 on 2026-02-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fournisseur_raison_sociale'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='api.client', verbose_name='Client concerné'),
        ),
    ]
