# Generated by Django 5.0.2 on 2026-02-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rotation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notedefrais',
            name='bl_awb',
        ),
        migrations.RemoveField(
            model_name='notedefrais',
            name='client_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='notedefrais',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='notedefrais',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='notedefrais',
            name='navire',
        ),
        migrations.RemoveField(
            model_name='notedefrais',
            name='tva',
        ),
        migrations.AlterField(
            model_name='notedefrais',
            name='expression_besoin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes_frais', to='api.expressionbesoin', verbose_name='Expression de besoin source'),
        ),
    ]
