# Generated by Django 5.0.2 on 2026-02-06 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_notedefrais_bl_awb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(unique=True, verbose_name='Référence BAD')),
                ('date', models.DateField(verbose_name="Date d'émission")),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('nom_representant', models.CharField(max_length=255, verbose_name='Nom du représentant')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bads', to='api.client')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bads', to='api.facture')),
            ],
            options={
                'verbose_name': 'Bon à Délivrer',
                'verbose_name_plural': 'Bons à Délivrer',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ItemBAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl', models.CharField(max_length=100, verbose_name='BL')),
                ('package_number', models.CharField(max_length=100, verbose_name='Nombre de colis')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Poids')),
                ('nombre_jours', models.PositiveIntegerField(default=0, verbose_name='Nombre de jours')),
                ('bad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.bad')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_items_crees', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_items_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de BAD',
                'verbose_name_plural': 'Items de BAD',
            },
        ),
    ]
