# Generated by Django 5.0.2 on 2026-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bad_itembad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembad',
            name='nombre_jours',
        ),
        migrations.AddField(
            model_name='bad',
            name='navire',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Navire'),
        ),
        migrations.AddField(
            model_name='bad',
            name='nombre_jours',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de jours'),
        ),
    ]
