# Generated by Django 5.0.2 on 2026-02-09 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_itembad_nombre_jours_bad_navire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad',
            name='reference',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Référence BAD'),
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='archives/%Y/%m/', verbose_name='Fichier joint')),
                ('type_doc', models.CharField(choices=[('BL', 'BL-CONNAISSEMENT'), ('MANIFESTE', 'MANIFESTE'), ('IMAGE', 'IMAGE')], max_length=20, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Note')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document archivé',
                'verbose_name_plural': 'Archives Documentaires',
                'ordering': ['-date_upload'],
            },
        ),
    ]
