# Generated by Django 5.0.2 on 2026-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bad_reference_documentarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionbesoin',
            name='affectation',
            field=models.CharField(default='Bureau siege', max_length=255, verbose_name='Affectation'),
        ),
        migrations.AddField(
            model_name='expressionbesoin',
            name='direction',
            field=models.CharField(default='Operation', max_length=100, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='expressionbesoin',
            name='nom_demandeur',
            field=models.CharField(default='Moustapha Seydna Aly', max_length=255, verbose_name='Nom du demandeur'),
        ),
    ]
