# Generated by Django 5.0.2 on 2026-02-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_expressionbesoin_affectation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionbesoin',
            name='client_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expressions_besoin', to='api.client', verbose_name='Client / Bénéficiaire'),
        ),
    ]
