# Generated by Django 5.0.2 on 2026-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_expressionbesoin_client_beneficiaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionbesoin',
            name='bl_awb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BL / AWB'),
        ),
        migrations.AlterField(
            model_name='expressionbesoin',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA (Estimated Time of Arrival)'),
        ),
        migrations.AlterField(
            model_name='expressionbesoin',
            name='navire',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Navire'),
        ),
    ]
