# Generated by Django 5.0.2 on 2026-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_expressionbesoin_bl_awb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationentrante',
            name='navire',
            field=models.CharField(default='MV-BRIALLANCE', max_length=100),
        ),
        migrations.AddField(
            model_name='rotationsortante',
            name='navire',
            field=models.CharField(default='MV-BRIALLANCE', max_length=100),
        ),
        migrations.AlterField(
            model_name='bad',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='bad',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='itemexpressionbesoin',
            name='type',
            field=models.CharField(choices=[('nourriture', 'Nourriture'), ('hebergement', 'Hébergement'), ('medicament', 'Médicament'), ('carburant', 'Carburant'), ('entretien', 'Entretien'), ('telecom', 'Télécom'), ('avance_salaire', 'Avance sur salaire'), ('avance_paiement', 'Avance sur paiement'), ('equipement', 'Equipement')], max_length=20),
        ),
    ]
