# Generated by Django 5.0.2 on 2026-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rotationentrante_navire_rotationsortante_navire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA (Estimated Time of Arrival)'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='etd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETD (Estimated Time of Departure)'),
        ),
    ]
