# Generated by Django 5.0.2 on 2026-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_devis_eta_alter_devis_etd'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationentrante',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
        migrations.AddField(
            model_name='rotationsortante',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
