# Generated by Django 5.0.2 on 2026-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rotationentrante_status_rotationsortante_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='bl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill of Lading'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='port_arrive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Port d'arrivée"),
        ),
        migrations.AlterField(
            model_name='devis',
            name='vessel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='voyage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
