# Generated by Django 5.0.2 on 2026-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_devis_bl_alter_devis_port_arrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='bl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill of Lading'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA (Estimated Time of Arrival)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='etd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETD (Estimated Time of Departure)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='port_arrive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Port d'arrivée"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='vessel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='voyage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
