# Generated by Django 5.0.2 on 2026-04-06 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_facture_bl_alter_facture_eta_alter_facture_etd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pda_number', models.CharField(max_length=50, unique=True, verbose_name='PDA N°')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.CharField(max_length=255)),
                ('vessel_name', models.CharField(max_length=255)),
                ('port_of_arrival', models.CharField(default='NOUAKCHOTT', max_length=255)),
                ('cargo_description', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar')], default='EUR', max_length=3)),
                ('number_of_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('apply_vat', models.BooleanField(default=True, verbose_name='Appliquer TVA (16%)')),
                ('remarks', models.TextField(blank=True, help_text='Texte libre pour les remarques en bas de page')),
            ],
        ),
        migrations.CreateModel(
            name='PDAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PORT_DUES', 'Ports Dues'), ('OTHER_EXPENSES', 'Other Expenses (Port Call Tax, etc.)'), ('STEVEDORING', 'Stevedoring/Handling on Board')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('grt_value', models.FloatField(default=0, help_text='Valeur GRT / Quantité / Tons')),
                ('rate', models.FloatField(default=0)),
                ('total_amount', models.FloatField(editable=False)),
                ('pda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pda')),
            ],
        ),
    ]
