# Generated by Django 5.0.2 on 2026-04-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pda_pdaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pda',
            name='customer',
        ),
        migrations.AddField(
            model_name='pda',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdas', to='api.client', verbose_name='Client / Principal'),
        ),
    ]
