# Generated by Django 5.0.2 on 2026-04-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_pda_customer_pda_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pda',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pda_creees', to=settings.AUTH_USER_MODEL),
        ),
    ]
