# Generated by Django 5.0.2 on 2026-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pda_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionbesoin',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='expressionbesoin',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='expressionbesoin',
            name='poids',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poids'),
        ),
        migrations.AddField(
            model_name='expressionbesoin',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='expressionbesoin',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume'),
        ),
    ]
