# Generated by Django 5.0.2 on 2026-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_expressionbesoin_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='facture',
            name='poids',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poids'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='facture',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume'),
        ),
    ]
