# Generated by Django 5.0.2 on 2026-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_facture_commentaire_facture_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemfacture',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
