# Generated by Django 5.0.2 on 2026-04-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_itemdevis_quantite_alter_itemfacture_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdevis',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemfacture',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
