# Generated by Django 5.0.2 on 2026-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_itemdevis_quantite_alter_itemfacture_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='is_excluding_customs',
            field=models.BooleanField(default=True, verbose_name='Exclure Custom and duties'),
        ),
        migrations.AddField(
            model_name='facture',
            name='is_excluding_customs',
            field=models.BooleanField(default=True, verbose_name='Exclure Custom and duties'),
        ),
        migrations.AddField(
            model_name='pda',
            name='voyage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pda',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poids'),
        ),
        migrations.AlterField(
            model_name='itemdevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemfacture',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
