# Generated by Django 5.0.2 on 2026-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_devis_is_excluding_customs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='moyen',
            field=models.CharField(blank=True, choices=[('cheque', 'Chèque'), ('virement', 'Virement'), ('espece', 'Espèce'), ('wallet', 'Wallet')], default='espece', max_length=20, null=True, verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de reçu'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('paye', 'Payée')], default='attente', max_length=20),
        ),
    ]
