# Generated by Django 5.0.2 on 2026-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_facture_date_paiement_facture_moyen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='reference_recu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Référence du reçu'),
        ),
    ]
