# Generated by Django 5.0.2 on 2026-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_facture_reference_recu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnotedefrais',
            name='type',
            field=models.CharField(choices=[('nourriture', 'Nourriture'), ('hebergement', 'Hébergement'), ('medicament', 'Médicament'), ('carburant', 'Carburant'), ('entretien', 'Entretien'), ('telecom', 'Télécom'), ('avance_salaire', 'Avance sur salaire'), ('avance_paiement', 'Avance sur paiement'), ('equipement', 'Equipement')], max_length=20),
        ),
    ]
