# Generated by Django 5.0.2 on 2026-04-27 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_itemnotedefrais_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fda_number', models.CharField(max_length=50, unique=True, verbose_name='FDA N°')),
                ('date', models.DateField(auto_now_add=True)),
                ('vessel_name', models.CharField(max_length=255)),
                ('port_of_arrival', models.CharField(default='NOUAKCHOTT', max_length=255)),
                ('cargo_description', models.TextField(blank=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poids')),
                ('voyage', models.CharField(blank=True, max_length=100, null=True)),
                ('port_inv_number', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar')], default='EUR', max_length=3)),
                ('apply_vat', models.BooleanField(default=True, verbose_name='Appliquer TVA (16%)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdas', to='api.client', verbose_name='Client / Principal')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fdas_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FDAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PORT_DUES', 'Ports Dues'), ('OTHER_EXPENSES', 'Other Expenses (Port Call Tax, etc.)'), ('STEVEDORING', 'Stevedoring/Handling on Board')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('grt_value', models.FloatField(default=0, help_text='Valeur GRT / Quantité / Tons')),
                ('rate', models.FloatField(default=0)),
                ('total_amount', models.FloatField(editable=False)),
                ('fda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.fda')),
            ],
        ),
    ]
