# Generated by Django 5.0.2 on 2026-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_fda_fdaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdaitem',
            name='devise',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Port invoice number'),
        ),
        migrations.AddField(
            model_name='fdaitem',
            name='port_inv',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Port invoice number'),
        ),
        migrations.AddField(
            model_name='fdaitem',
            name='price_devise',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price in Devise'),
        ),
        migrations.AddField(
            model_name='fdaitem',
            name='price_mru',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price in MRU'),
        ),
    ]
